### ISSUE TITLE
error with UltimateSDUpscale

### ISSUE THREAD

**Issue by za-wa-n-go** [gameltb/Comfyui-StableSR#1]
```
[StableSR] fix_color
[StableSR] Error fix_color: The size of tensor a (1496) must match the size of tensor b (1490) at non-singleton dimension 2
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "X:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 96, in get_output_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by toasterlint** [comment]
This error seems to only happen when using the "Wavelet" option in the StableSRColorFix node.  Using "AdaIN" is working fine.
